In [1]:
import pandas as pd

In [18]:
classes = pd.read_csv('sky_fall_2022_classes.csv')

In [20]:
classes.columns = classes.iloc[1]

In [25]:
classes

1,CRN,Subj,Crse,Sec,Title,Dates,Days,Time,Instructor,Units,NaN,Bldg,Room,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Web,Web,Hybrid,Learn
1,CRN,Subj,Crse,Sec,Title,Dates,Days,Time,Instructor,Units,NaN,Bldg,Room,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Based,Asst,Comm,NaN
3,80005,ACTG,100,JA,Accounting Procedures,08/17-12/14,W,1830 - 2130,"Viertel, Clayton Tony",3,3,2-08,8211,NaN,NaN,NaN
4,80006,ACTG,100,OLH,Accounting Procedures,08/17-12/17,NaN,-,"Zhang, Hellen Li Tian",3,3,2-ONLN,0,Y,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1154,97683,WELL,723,OSH,Ayurvedic Aromatherapy,10/17-12/10,NaN,-,"Wimmer, Ronda R",1,2-ONLN,0,Y,NaN,NaN,NaN
1155,95021,WELL,725,OLH,Consciousness/Intnt/Meditation,08/17-12/17,NaN,-,"Wimmer, Ronda R",3,2-ONLN,0,Y,NaN,NaN,NaN
1156,95926,WELL,742,OLH,Herbal/Botanical Med/Ethnobot,08/17-12/17,NaN,-,"Egan, Catherine Phyllis",3,2-ONLN,0,Y,NaN,NaN,NaN
1157,97696,WELL,743,OLH,Holistic Nutrition/Functional,08/17-12/17,NaN,-,"Wimmer, Ronda R",3,2-ONLN,0,Y,NaN,NaN,NaN
1158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38,of,38,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
classes.drop(classes['CRN' == 'NaN'].index)

KeyError: False